lang: en-gb
name: Peter Larkin
title: Peter Larkin
type: website
url: https://peterlarkin.co.uk
image: https://peterlarkin.co.uk/assets/static/share-image.png
description: Motivated by a desire to solve real-world problems, I bring a mix of strategic thinking, creative ideas and executional detail to help create work that's bold and meaningful.
clients:
  - Age UK
  - BAFTA
  - BBC
  - Ben & Jerry's
  - Breast Cancer Now
  - British Heart Foundation
  - Canal and River Trust
  - Chatham House
  - Citizens Advice
  - Co-op
  - Compassion in World Farming
  - Dogs Trust
  - Feeding America
  - Greenpeace
  - The Guardian
  - Heineken
  - IKEA
  - innocent
  - London Fire Brigade
  - Macmillan
  - Mars
  - Mozilla
  - MSC
  - NCT
  - Nike
  - Nesta
  - The New York Times
  - parkrun
  - Penguin Random House
  - The Prince's Trust
  - PwC
  - Rainforest Alliance
  - Refugee Action
  - RSPO
  - Sainsbury's
  - Sarcoma UK
  - Sky
  - The Start Network
  - Sustrans
  - thredUP
  - Tommy's
  - Ugly Drinks
  - UNDP
  - Unilever
  - VSO International
  - Wellcome Trust
  - WWF
  - YMCA
