name: Eleventy Build
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: peterlarkin/actions-eleventy@v2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site
          github_token: ${{ secrets.GITHUB_TOKEN }}
